<?php
$names = array (
  'captcha' => '验证码',
  'captcha-j' => '验证码新第2种',
  'captcha-new' => '验证码新第3种',
  'catalog' => '行业分类',
  'catalog-job' => 'job分类',
  'catalog-mall' => 'mall-商城分类',
  'comment' => '评论调用',
  'comment_buy' => '采购页评论',
  'contact' => '联系方式收费',
  'content' => '内容收费',
  'guest_contact' => '游客联系方式',
  'guest_contactnew' => '游客联系方式new',
  'letter' => '字母索引',
  'line' => '会员状态',
  'password' => '密码输入',
  'password-new' => '密码输入-new',
  'player' => '视频播放',
  'poll' => '行业票选',
  'property' => '分类属性',
  'property_js' => '分类属性JS',
  'push' => '消息推送',
  'question' => '验证问题',
  'user' => '会员登录',
  'vote' => '投票调用',
  'weibo' => '微博同步',
);
?>