<?php
$names = array (
  'ad' => '广告',
  'ad_code' => '广告代码',
  'ad_code-buy' => '供，求，企，品，招，展，人才大幻灯专用模板',
  'ad_code-mall' => '商城大幻灯专用模板',
  'ad_view' => '广告预览',
  'announce' => '公告',
  'archiver' => '无图版',
  'comment' => '评论',
  'comment_list' => '评论列表',
  'feed' => 'RSS订阅',
  'form' => '表单',
  'gift' => '积分换礼',
  'giftindex' => '积分换礼首页',
  'guestbook' => '留言本',
  'link' => '友情链接',
  'mobile' => '手机版介绍',
  'poll' => '票选',
  'poll_show' => '票选内容',
  'sitemap' => '网站地图',
  'spread' => '排名推广',
  'spread_code' => '推广代码',
  'view' => '查看大图',
  'vote' => '投票',
  'webpage' => '单网页',
  'webpage-contact' => '联系我们',
);
?>